### ISSUE TITLE
Add phrase breaker "—"

### ISSUE THREAD

**Issue by AlexeyCAT** [mltony/nvda-sentence-nav#12]
Please add next phrase breaker "—". Thank you.

**Comment by mltony** [comment]
You can configure phrase breakers in addon preferences.

**Comment by AlexeyCAT** [comment]
Thank you. I found it and added needed symbol after your reply. I don't 
find it earlier because all elements after "Take Wikipedia-style 
references into account" are hidden. They could be accessed via tab key 
but not visually.
