### ISSUE TITLE
Addon doesn't work properly in Notepad plus plus.

### ISSUE THREAD

**Issue by AlexeyCAT** [mltony/nvda-sentence-nav#13]
Hi! When i press Alt plus Up addon don't go to previous sentence. Maybe i should check some settings in notepad plus plus? Can you help?

**Comment by AlexeyCAT** [comment]
Now it work like it should. I don't know why. Sorry.

**Comment by mltony** [comment]
In v2.9 I fixed an issue with Notepad++. The issue was that the cursor was not moving correctly in presence of Unicode characters, e.g. Russian. If it still bothers you, try new version.

**Comment by AlexeyCAT** [comment]
Thank you!
