### ISSUE TITLE
In Visual Studio Code, NVDA often starts at the top of a document

### ISSUE THREAD

**Issue by jhomme** [mltony/nvda-sentence-nav#14]
### 

To reproduce:

*  create a Markdown document or a text document in Visual Studio code. Put the cursor in the middle of the document and use sentence reading keys. 
* Expected behavior, NVDA would read sentences starting where the cursor is now.
* Actual behavior, sentence reading happens from somewhere else in the document.

**Comment by mltony** [comment]
This is a problem of VSCode. For screenreader interaction they don't 
show the whole document in the edit box, but rather they only load parts 
of document near the cursor. SentenceNav assumes that the whole document 
is present and that the document doesn't change while the new sentence 
is being computed. Both these assumptions are violated with VSCode, so 
it would be impossible to make SentenceNav to work with VSCode at the 
moment.
