### ISSUE TITLE
Sentence Nav 2.12 incompatible with NVDA 2019.2

### ISSUE THREAD

**Issue by CyrilleB79** [mltony/nvda-sentence-nav#22]
Hi Tony,

Sentence Nav 2.12 is advertised to be compatible with NVDA 2019.2. However when I run it with NVDA 2019.2.1, I get the following error:

```
ERROR - globalPluginHandler.listPlugins (15:19:52.892):
Error importing global plugin sentenceNav
Traceback (most recent call last):
  File "globalPluginHandler.pyo", line 22, in listPlugins
  File "C:\Users\Cyrille\AppData\Roaming\nvda\addons\SentenceNav\globalPlugins\sentenceNav.py", line 38
    print(str(s), file=f)
                      ^
SyntaxError: invalid syntax

```

Could you please fix this in the next release?

Since NVDA 2019.2.1 is already old, I would recommend fixing the issue just by changing the compatibility range starting from 2019.3 onwards instead.

**Comment by lukaszgo1** [comment]
Just for reference, if the aim is to remain compatible with 2019.2 you can put `from __future__ import print_function` at the top of the file, and this error would go away.
