### ISSUE TITLE
Request to release an add-on compatible with NVDA-2023.1

### ISSUE THREAD

**Issue by cary-rowen** [mltony/nvda-sentence-nav#27]
For sentence-nav and word-Nav, I believe that it can be compatible with the new version of NVDA without making too many changes to the source code.
I know you are very busy, how can I help to make these add-ons compatible with NVDA-2023.1?
Especially the latest version of the add-on template, which require only minor changes to automatically release new versions, if you need me to make template for these add-ons, please let me know.

Thanks

**Comment by mltony** [comment]
I can give you access to my repositories - you can update template and 
make a new release. Would you be interested?

**Comment by cary-rowen** [comment]
Of course, I am very willing to do these things. My Email: manchen_0528@outlook.com

**Comment by mltony** [comment]
I just granted you access to sentenceNav add-on. I appreciate your help!

Let me know if you can also help releasing compatible versions of my 
other add-ons.

**Comment by cary-rowen** [comment]
Hi,

I'm happy to update the templates and release new versions for the following add-ons: sentence-nav, tonys-enhancements, word-nav, bluetooth-audio, browser-nav.

Thanks for your trust

**Comment by cary-rowen** [comment]
If so, would you like me to keep these addons updated on the NVDA addons community site as well?

**Comment by mltony** [comment]
I just granted you access to those 5 repositories. Yes, updating on NVDA 
site would be great.

**Comment by cary-rowen** [comment]
Thanks, I will do that. Let me know if you have any release plans or ideas for these add-ons.
