### ISSUE TITLE
If not in an edit field, pass keys to NVDA

### ISSUE THREAD

**Issue by jhomme** [mltony/nvda-sentence-nav#3]
The add-on tries to find sentences in list boxes and combo boxes. ALT+DownArrow and ALT+UpArrow are normal Windows keys in those situations. Can the add-on ignore these keys in those situations?

**Comment by mltony** [comment]
SentenceNav definitely passes through Alt+Up?Down in ComboBoxes. Since version 2.0 I think it also passes them through in List views. If you still encounter any cases when it doesn't happen - please send me step-by-step instruction how to reproduce this issue.
