### ISSUE TITLE
Turn to Forny Malykh: indentNav: Should indentNave be translated using the NVDA translation system?

### ISSUE THREAD

**Issue by dingpengyu** [mltony/nvda-sentence-nav#4]
Noelia Ruiz
Dear Tony: indentNav add-on is not added to the translation system used by NVDA, but chinese translators have tried to translate it. Would you like your add-on is added to this system?
If so, please let us know.
My pending work regarding to add-ons for this weekend is:
1. Final review for vlc to post the new version on the website.
2. If you want, add your add-on to a repo on Bitbucket so that translators can work translating it.
Thanks
Original address Mostly for Tony Malykh: indentNav: Should indentNave be translated using the NVDA translation system? 
https://nvda-addons.groups.io/g/nvda-addons/topic/mostly_for_tony_malykh/22252127?p=,,,20, 0,0,0::recentpostdate%2Fsticky,,,20,2,40,22252127

**Comment by mltony** [comment]
I believe both SentenceNav and IndentNav have been added to translation system since then.
