### ISSUE TITLE
SentenceNav 2.5 doesn't run with NVDA 2018.1

### ISSUE THREAD

**Issue by DrSooom** [mltony/nvda-sentence-nav#7]
The "manifest.ini" says that SentenceNav 2.5 is compatible to NVDA 2018.1.0, but it definitively doesn't run with NVDA 2018.1. I tried it on my installed 2018.1 by updating SentenceNav from 1.1 to 2.5 as well as installing it with a new, clean portable version of NVDA 2018.1.

Well, NVDA 2018.1 Portable hangs directly on installing/uninstalling the add-on if you choose the option to restart NVDA right now. You must kill the process "nvda.exe" manually via the Task Manager to be able to launch NVDA again. And if you restart NVDA later, the restart process works as it should, but not SentenceNav – even if it's listed in the Add-ons Manager with "Running" status. There is also no entry in the NVDA menu.

Perhaps SentenceNav 2.5 requires NVDA 2018.2 due to the changes in the NVDA menu between 2018.1 and 2018.2.

PS: It seems to work as it should with NVDA 2019.2.1 Portable based on a quick test. And the settings of SentenceNav 2.5 look very fine. 😀

**Comment by mltony** [comment]
At this point I no longer support SentenceNav version 2.5 - as NVDA is 
about to switch to python 3 in a few months, I only maintain the Python 
3 version.

**Comment by cary-rowen** [comment]
Currently the add-on is compatible from NVDA-2019.3 to NVDA-2023.1
